export const LOGIN_FAILED='LOGIN_FAILED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAILED='REGISTER_FAILED';
export const GET_ERROR='GET_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';